spring:
  application:
    name: nexo
  datasource:
    url:  jdbc:postgresql://localhost:5432/NexoDB
    user: postgres
    password: 26122006
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none